name: CDK Testing

on:
  pull_request:
    branches: [main]

env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  test_cdk:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: serverless
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: install dependencies serverless
        run: npm i
      - name: run test
        run: npm test
