name: Deploy CloudFormation

on:
  push:
    branches: [main]

env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  Deploy_CDK:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: serverless
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: install dependencies
        run: npm install
      - name: install CDK cli
        run: npm install -g aws-cdk
      - name: Create CloudFormation Template
        run: cdk synth
      - name: Deploy CDK Stack
        run: cdk deploy
