name: Deploy Front 2 S3

on:
  push:
    branches: [main]

env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  Deploy_Front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Upload Front 2 S3 Bucket
        uses: ./S3
        with:
          FrontDir: front
          BuildDir: build
          S3BucketName: dictionary.elaygelbart.com
          useDelete: true
