name: E2E Testing

on:
  pull_request:
    branches: [main]

jobs:
  test_server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm i
      - run: npm start
      - run: npm run test
