name: Server Side Testing

on:
  push:
    branches: [CICD2]

jobs:
  test_server:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: serverless/back
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install
      - run: npm run test
