name: Server Side Testing

on:
  pull_request:
    branches: [main]

jobs:
  test_server:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["12", "14", "16"]
    name: Node ${{ matrix.node }} sample
    defaults:
      run:
        working-directory: serverless/back
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm test
